using System;
using UnityEngine;

namespace Game.Runtime.World
{
    /// <summary>
    /// The catalogue of imported third-party meshes and clips
    /// (Assets/ThirdParty/**), generated by the editor menu
    /// GNP > Rebuild Asset Kit into Assets/Settings/Resources/AssetKit.asset.
    ///
    /// Every mesh in it has already been baked to vertex colours from the
    /// kit's colormap and quantised to Palette.Town by KitImport, so it
    /// renders through the one GNP/VertexColor material like everything
    /// ProcMesh builds. Runtime code asks by key and always keeps a
    /// procedural fallback: the game builds and runs without the packs.
    ///
    /// Keys are the path below Assets/ThirdParty, lower-cased, without the
    /// vendor's format folders and the extension:
    ///   kenney/city-kit-suburban/building-type-a
    ///   kenney/car-kit/sedan
    ///   kenney/interface-sounds/click_001
    ///   freesound/485621-protest-crowd
    /// </summary>
    public sealed class AssetKit : ScriptableObject
    {
        public const string ResourceName = "AssetKit";

        /// <summary>One mesh of a model, with its transform relative to the model root.</summary>
        [Serializable]
        public struct Part
        {
            public Mesh Mesh;
            public Vector3 LocalPosition;
            public Quaternion LocalRotation;
            public Vector3 LocalScale;
        }

        /// <summary>An empty transform in the model (a wheel seat, a door hinge).</summary>
        [Serializable]
        public struct Attachment
        {
            public string Name;
            public Vector3 LocalPosition;
            public Quaternion LocalRotation;
        }

        [Serializable]
        public struct MeshEntry
        {
            public string Key;
            public Part[] Parts;
            public Attachment[] Attachments;
            /// <summary>Union of the parts' bounds in the model's space, feet at y = 0.</summary>
            public Bounds Bounds;
            public int Triangles;
        }

        [Serializable]
        public struct ClipEntry
        {
            public string Key;
            public AudioClip Clip;
        }

        public MeshEntry[] Meshes = new MeshEntry[0];
        public ClipEntry[] Clips = new ClipEntry[0];

        private static AssetKit _instance;
        private static bool _tried;

        /// <summary>The kit asset, or null when it was never generated.</summary>
        public static AssetKit Instance
        {
            get
            {
                if (!_tried)
                {
                    _tried = true;
                    _instance = Resources.Load<AssetKit>(ResourceName);
                }
                return _instance;
            }
        }

        public static bool TryGetMesh(string key, out MeshEntry entry)
        {
            AssetKit kit = Instance;
            if (kit != null)
            {
                for (int i = 0; i < kit.Meshes.Length; i++)
                {
                    if (kit.Meshes[i].Key != key) continue;
                    entry = kit.Meshes[i];
                    return entry.Parts != null && entry.Parts.Length > 0 && entry.Parts[0].Mesh != null;
                }
            }
            entry = default;
            return false;
        }

        public static bool TryGetClip(string key, out AudioClip clip)
        {
            AssetKit kit = Instance;
            if (kit != null)
            {
                for (int i = 0; i < kit.Clips.Length; i++)
                {
                    if (kit.Clips[i].Key != key || kit.Clips[i].Clip == null) continue;
                    clip = kit.Clips[i].Clip;
                    return true;
                }
            }
            clip = null;
            return false;
        }

        /// <summary>Spawns a model: one GameObject per part under a root at
        /// pos, turned yawDeg about y. Parts use the opaque vertex-colour
        /// material; colliders are MeshColliders on the parts.</summary>
        public static GameObject Spawn(in MeshEntry entry, string name, Transform parent,
            Vector3 pos, float yawDeg, bool collider)
        {
            var root = new GameObject(name);
            if (parent != null) root.transform.SetParent(parent, false);
            root.transform.localPosition = pos;
            root.transform.localRotation = Quaternion.Euler(0f, yawDeg, 0f);
            for (int i = 0; i < entry.Parts.Length; i++)
            {
                Part p = entry.Parts[i];
                if (p.Mesh == null) continue;
                GameObject go = MatLib.Spawn(p.Mesh.name, p.Mesh, root.transform, p.LocalPosition, collider);
                go.transform.localRotation = p.LocalRotation;
                go.transform.localScale = p.LocalScale;
            }
            return root;
        }

        /// <summary>World-space plan footprint of a model placed at pos with
        /// yawDeg, as a y-up Bounds (yaw is rounded to the nearest 90°, which
        /// is how the town places things).</summary>
        public static Bounds Footprint(in MeshEntry entry, Vector3 pos, float yawDeg)
        {
            Vector3 size = entry.Bounds.size, centre = entry.Bounds.center;
            int quarter = Mathf.RoundToInt(yawDeg / 90f) & 3;
            if ((quarter & 1) == 1)
            {
                size = new Vector3(size.z, size.y, size.x);
                centre = new Vector3(quarter == 1 ? centre.z : -centre.z, centre.y, quarter == 1 ? -centre.x : centre.x);
            }
            else if (quarter == 2) centre = new Vector3(-centre.x, centre.y, -centre.z);
            return new Bounds(pos + centre, size);
        }

        private static readonly System.Collections.Generic.Dictionary<string, Mesh> _combined =
            new System.Collections.Generic.Dictionary<string, Mesh>();

        /// <summary>All parts of a model welded into one mesh in the model's
        /// space (a car with its four wheels), cached per key: what a figure
        /// or a parked car needs when it wants one renderer.</summary>
        public static bool TryGetCombined(string key, out Mesh mesh)
        {
            if (_combined.TryGetValue(key, out mesh) && mesh != null) return true;
            if (!TryGetMesh(key, out MeshEntry entry)) { mesh = null; return false; }
            var combine = new CombineInstance[entry.Parts.Length];
            for (int i = 0; i < entry.Parts.Length; i++)
            {
                Part p = entry.Parts[i];
                combine[i].mesh = p.Mesh;
                combine[i].transform = Matrix4x4.TRS(p.LocalPosition, p.LocalRotation, p.LocalScale);
            }
            mesh = new Mesh { name = key + " (combined)" };
            mesh.CombineMeshes(combine, true, true);
            mesh.RecalculateBounds();
            _combined[key] = mesh;
            return true;
        }

        public static bool TryFindAttachment(in MeshEntry entry, string prefix, int index, out Attachment att)
        {
            int n = 0;
            if (entry.Attachments != null)
            {
                for (int i = 0; i < entry.Attachments.Length; i++)
                {
                    if (!entry.Attachments[i].Name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)) continue;
                    if (n++ == index) { att = entry.Attachments[i]; return true; }
                }
            }
            att = default;
            return false;
        }
    }
}
